# nameof the executable: 0-hreadelf, 1-hreadelf, 2-hreadelf
# rules: all
# CC: the compiler to be used
# SRC: the .c files listed
# OBJ: the .o files, not listed
# NAME: the name of the executable

CC = gcc
SRC = main.c holberton.c
OBJ = $(SRC:.c=.o)
NAME = holberton


all: 
